[project]
name = "average"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "synnax>=0.49.0",
    "termcolor>=3.2.0",
    "yaspin>=3.4.0",
]
